### ISSUE TITLE
Нашел способ добавить улицы и районы.

### ISSUE THREAD

**Issue by aios** [h-zone/vk-geo-collector#2]
Правда не совсем апишным путем.

**Comment by h-zone** [comment]
Да в принципе оно и не нужно по сути, это не кладр и не фиас.
Это тупо статика для хранения указателей на город, что удобно использовать для поиска пользователей по городу/стране/региону проживания да и в целях таргетинга какого-либо удобство, чтобы данные жили под рукой.
